[package]
name = "hdf5"
version = "0.6.1"  # !V
authors = ["Ivan Smirnov <i.s.smirnov@gmail.com>"]
keywords = ["hdf5"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "Thread-safe Rust bindings for the HDF5 library."
repository = "https://github.com/aldanor/hdf5-rust"
homepage = "https://github.com/aldanor/hdf5-rust"
build = "build.rs"
edition = "2018"

[features]
default = []
mpio = ["mpi-sys", "hdf5-sys/mpio"]

[workspace]
members = ["hdf5-types", "hdf5-derive", "hdf5-sys"]
exclude = ["*.yml", "ci/*"]

[dependencies]
bitflags = "1.1"
lazy_static = "1.3"
libc = "0.2"
parking_lot = "0.10.0"
ndarray = "0.12"
num-integer = "0.1"
num-traits = "0.2"
mpi-sys = { version = "0.1", optional = true }
hdf5-sys = { path = "hdf5-sys", version = "0.6.1" }  # !V
hdf5-types = { path = "hdf5-types", version = "0.6.1" }  # !V
hdf5-derive = { path = "hdf5-derive", version = "0.6.1" }  # !V

[dev-dependencies]
mashup = "0.1"
pretty_assertions = "0.6"
rand = { version = "0.7", features = ["small_rng"] }
regex = "1.3"
scopeguard = "1.0"
tempdir = "0.3"

[build-dependencies]
hdf5-sys = { path = "hdf5-sys", version = "0.6.1" }  # !V
